baseURL = "https://hadim.fr"
languageCode = "en-us"
title = "Hadrien Mary"
publishDir = "docs"
theme = "researcher"

disableKinds = ["taxonomy", "term", "RSS", "sitemap", "robotsTXT"]
enableEmoji = true

[params]
  author = "Hadrien Mary"
  description = "Personal website"
  favicon = "favicon.ico"

  [params.footer]
    text = "Hugo Researcher Theme"
    url = "https://github.com/ojroques/hugo-researcher"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 1
  [[menu.main]]
    name = "Resume"
    url = "/resume.pdf"
    weight = 2
  [[menu.main]]
    name = "Credits"
    url = "/credits"
    weight = 3

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
